### ISSUE TITLE
Steering Position Popup

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#120]
Whenever in steering mode, bring a pop-up of a top down 2D picture of the rover (just a box) that would show the current wheel position of an the rover. And potentially an arrow showing the direction. 

-Keyton

**Comment by amwgvf** [comment]
Attempting to resolve with [feature\steering](https://github.com/MissouriMRDT/BaseStation_Software/tree/feature/steering) branch
