### ISSUE TITLE
Reduce 3D Rover refresh rate and render error

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#132]
The 3D rover component re-renders many times a second when it starts to receive new data from the IMU. When there are multiple 3D rovers components open (1 in RED and 1 in RID), this re-rendering causes the component to _give up_ and it stops attempting to redraw until it can catch up. Reducing the send rate of the IMU to once every 200ms resolves the issue, but if a third 3D rover component was to be opened, the issue would resurface.

There is also an occasional, undiagnosed error upon closure of the 3D rover in RID

**Comment by for-a-greener-dawn** [comment]
No longer a relevant problem as the component had most of its screwiness fixed and inertial measurement data is currently not an available feature on this year's rover
