### ISSUE TITLE
Correct RON components default size

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#134]
The custom packets and packet logger components require a re-render before they properly scale down / up to the correct size if the screen size is different than REDs

**Comment by for-a-greener-dawn** [comment]
So it's written down:
The issue stems from the RON window being appended to the list of windows _after_ the RON component is constructed. I attempted a window resize listener, but current lack of knowledge on how to deal with "window" being a list is causing resize listeners to not trigger

**Comment by for-a-greener-dawn** [comment]
Fixed by removing the `RONModuleWidth` property. The components are more statically sized now, but the accommodation for flexibility was excessively complex when the window just needs to fit on the Basestation computer's monitors
