### ISSUE TITLE
Remove or normalize y-axis of the all science graphs option

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#135]
The science sensors each measure very different data on very different orders of magnitude. The ppm of O2 in the air may be well into the hundreds of thousands, while the desired concentration of methane is the single-digit percent's. When looking at all these trends at the same time, the vast majority of data is lost due to the bad scaling. The crosshair functionality can give the scientists the exact actual numbers, so the view should be optimized for spotting trends.

**Comment by thomas-gleiforst** [comment]
Attempted to be resolved by 840aec531e3ae2eff554fa39505ae49f9134552b

**Comment by ThisIsBrady** [comment]
Resolved in #191
