### ISSUE TITLE
Add next autonomy target to map

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#142]
Either having a separate image or a reserved color on the main map for the next waypoint that autonomy is approaching (as reported by autonomy) or a dedicated map in the autonomy view would make it a lot clearer what Autonomy is actually attempting to do during a task.

**Comment by ThisIsBrady** [comment]
Dedicated map in the Autonomy RAM page with waypoint path and telemetry is preferable at this point.
