### ISSUE TITLE
Update geneva position readout even using velocity control

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#148]
It is hasn't been explored if this is a _when electricals send the position packet_ issue or a _when basestation looks for and updates the geneva position_ issue, but regardless, the readout in RAM should match the actual test tube position, even if it is being controlled through the velocity control or by another client.

**Comment by for-a-greener-dawn** [comment]
Geneva is no longer supported as the geneva mechanism is not a component of 2022's rover
