### ISSUE TITLE
Add rover selection option

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#152]
An option to select the desired rover to be controlled and load a slightly different application would help make it easier to test newer features on older rovers. Ideally, this would only switch out essential components like the manifest and the rover.stl while leaving as much else alone as possible so that basestation can be thoroughly and easily tested on a past rover.

This feature becomes even more important if RoveComm3 is developed for Aurora or 2021-2022, as it would be preferable to not drop all support for older rovers.

However! It should be noted this is a stretch goal and should be thoroughly discussed before perusing, as it has been an active decision of the team in the past to **not** put much effort into supporting old rovers so that we can focus on this years rover - if you want to control an old rover, that is what the software releases are for. This should only be perused if it is truly valuable to use old rovers as a testing platform or their is other motivation to use old platforms with new software.

**Comment by for-a-greener-dawn** [comment]
No longer a desired feature
