### ISSUE TITLE
3D Rover Fading

### ISSUE THREAD

**Issue by amwgvf** [MissouriMRDT/BaseStation_Software#158]
Due to adding another light source to the 3D rover, when it updates it fades completely white and we can't see it. Some possible solutions could be changing the color of the background to something other than white, so that we can see the 3D rover. Or we could try to find another solution to avoid the fading entirely.

**Comment by rkbhkp** [comment]
Changing the background color is a quick fix and is not a solution to this problem. One fix is to remove the second light source, it doesn't have this problem when there is only one (although I think it sometimes has a problem where it will delete the light source and the rover is too dark when there is only one).

 Another fix is to find a way for it to remove both light sources each time it updates. Currently, the code works by deleting the light source and then making a new one each time the rover model updates.There might be a way to go about deleting both light sources/cameras.

Not needing to make a new camera/light source each time it updates and have it only ever make one of each is also another solution (this is probably the best choice)
