### ISSUE TITLE
Temporarily add Valkyrie BMS options

### ISSUE THREAD

**Issue by amwgvf** [MissouriMRDT/BaseStation_Software#159]
We need a hacky solution for the time being, so that if necessary during a task, we can kill the battery from Basestation. In the future we'll need a more permanent fix but for our mock comp we should implement this quickly due to the likelihood of getting rained on.

**Comment by for-a-greener-dawn** [comment]
Changes to enable communication with Valkyrie's BMS board is currently (5/18/2021) hamfisted into the URC branch. If a more elegant option is desired in the future (such as a drop down or a button that opens a submenu), the old (valkyrie) rovecomm manifest will need to be included in the Electron Asset file.
