### ISSUE TITLE
Camera Color and perspective Problems 

### ISSUE THREAD

**Issue by rkbhkp** [MissouriMRDT/BaseStation_Software#164]
Most if not all of the cameras have very poor color and depth perception. This made it difficult for many of the tasks needed during competition. Something to look into would be better cameras or if there is a way to improve how they look (maybe there is a lot of compression or something else that makes them look bad?)

**Comment by for-a-greener-dawn** [comment]
So far this issue is being addressed by gimble mount redesigns, and auto-brightness and contrast settings on the camera pi's

**Comment by for-a-greener-dawn** [comment]
This issue has been addressed and largely fixed with a total camera software overhaul that has enabled very adaptable control of the cameras and better network use
